//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 11:02:04 AM MEZ 
//


package main.java.core.mapper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.core.mapper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatementsIdMapper_QNAME = new QName("", "statementsIdMapper");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.core.mapper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatementIdMapper }
     * 
     */
    public StatementIdMapper createStatementIdMapper() {
        return new StatementIdMapper();
    }

    /**
     * Create an instance of {@link StatementsIdMapper }
     * 
     */
    public StatementsIdMapper createStatementsIdMapper() {
        return new StatementsIdMapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatementsIdMapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statementsIdMapper")
    public JAXBElement<StatementsIdMapper> createStatementsIdMapper(StatementsIdMapper value) {
        return new JAXBElement<StatementsIdMapper>(_StatementsIdMapper_QNAME, StatementsIdMapper.class, null, value);
    }

}
