//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 11:02:04 AM MEZ 
//


package main.java.core.mapper;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statementsIdMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statementsIdMapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statementIdMapper" type="{}statementIdMapper" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "statementsIdMapper")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statementsIdMapper", propOrder = {
    "statementIdMapper"
})
public class StatementsIdMapper {

    @XmlElement(nillable = true)
    protected List<StatementIdMapper> statementIdMapper;

    /**
     * Gets the value of the statementIdMapper property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementIdMapper property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementIdMapper().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatementIdMapper }
     * 
     * 
     */
    public List<StatementIdMapper> getStatementIdMapper() {
        if (statementIdMapper == null) {
            statementIdMapper = new ArrayList<StatementIdMapper>();
        }
        return this.statementIdMapper;
    }

}
