//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 11:02:04 AM MEZ 
//


package main.java.core.mapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statementIdMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statementIdMapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statementOnline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="statementOffline" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "statementIdMapper")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statementIdMapper", propOrder = {
    "statementOnline",
    "tagName"
})
public class StatementIdMapper {

    protected String statementOnline;
    protected String tagName;
    @XmlAttribute
    protected String statementOffline;
    
    public StatementIdMapper() {
    	
    }
    
    public StatementIdMapper(String attrValue, String stOnline, String tag) {
    	this.setStatementOffline(attrValue);
    	this.setStatementOnline(stOnline);
    	this.setTagName(tag);
    }

    /**
     * Gets the value of the statementOnline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatementOnline() {
        return statementOnline;
    }

    /**
     * Sets the value of the statementOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatementOnline(String value) {
        this.statementOnline = value;
    }

    /**
     * Gets the value of the tagName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagName(String value) {
        this.tagName = value;
    }
    
    
    /**
     * Gets the value of the statementOffline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatementOffline() {
        return statementOffline;
    }

    /**
     * Sets the value of the statementOffline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatementOffline(String value) {
        this.statementOffline = value;
    }

}
